### ISSUE TITLE
Android app sometimes crash at LocationListener.onStatusChanged

### ISSUE THREAD

**Issue by sanak** [geopaparazzi/smash#151]
Sometimes I encounter the Android app crash on our gtt-project fork `gtt/develop` branch, and I confirmed that this is also reproducible on Google Play latest version (v1.7.0).

- Android device: ASUS ZenFone (X00RD)
- Android version: 8.0.0
- SMASH app version: 1.7.0 (from Google Play installation)

Logcat log (from Android Studio View/Tool Windows/Logcat menu):
```
:
2021-09-21 23:03:44.359 19111-20210/? E/IzatSvc_PassiveLocListener: Exiting with error onLocationChanged line 152 "1"
2021-09-21 23:03:46.361 19111-20210/? E/IzatSvc_PassiveLocListener: Exiting with error onLocationChanged line 152 "1"
2021-09-21 23:03:47.362 19208-19331/? E/XTCC-6.1.2.10: [FDAL_OSListener] handleLocationUpdate:  failed: 2
2021-09-21 23:03:47.374 13300-13300/? D/AndroidRuntime: Shutting down VM
2021-09-21 23:03:47.375 13300-13300/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: eu.hydrologis.smash, PID: 13300
    java.lang.AbstractMethodError: abstract method "void android.location.LocationListener.onStatusChanged(java.lang.String, int, android.os.Bundle)"
        at android.location.LocationManager$ListenerTransport._handleMessage(LocationManager.java:304)
        at android.location.LocationManager$ListenerTransport.-wrap0(Unknown Source:0)
        at android.location.LocationManager$ListenerTransport$1.handleMessage(LocationManager.java:242)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:169)
        at android.app.ActivityThread.main(ActivityThread.java:6595)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
2021-09-21 23:03:47.381 19501-19521/? I/ActivityManager: Showing crash dialog for package eu.hydrologis.smash u0
```

**Comment by moovida** [comment]
Hi @sanak , can you tell me a way to reproduce this? I really hope it is not random....

**Comment by sanak** [comment]
@moovida (CC: @mbasa, @dkastl)  
I still can't find the reproducible steps, but I felt that `background_locator` seemed to have the same issue until 3 June,
- Issue: https://github.com/rekab-app/background_locator/issues/241
- commit: https://github.com/rekab-app/background_locator/commit/e1976597d14a1bf28c7c05a29215ecfcf4225496

and the update seemed to be applied to smash side at 23 Aug,
- commit-diff: https://github.com/geopaparazzi/smash/commit/2ad857ca4e8ab111fef74b115f80c86919560bbb#diff-8b7e9df87668ffa6a04b32e1769a33434999e54ae081c52e5d943c541d4c0d25

Our `gtt/develop` branch and official released Google Play store versions use ">= 1.7.0+61" at 24 Aug which includes above `background_locator` update (=latest) already, so I guess that there may be still similar issue on `background_locator` side.

I will try to check whether this issue is also reproducible on `background_locator` example app side, then create a new issue on `background_locator` side, later.

**Comment by frafra** [comment]
@sanak how is it going?

**Comment by sanak** [comment]
I still haven't checked it... 🙇 
I am on Japan Golden Week vacation until this weekend, so I will check it after next week.

**Comment by sanak** [comment]
Sorry for late reply, but I couldn't reproduce this issue (at least until my Intel MacBook Pro itself crashed by hardware reason...😅 ), so I close this issue, once.
If I encounter the same issue in future, I will reopen this.
Thanks,
