### ISSUE TITLE
Crash when creating a new GPS log

### ISSUE THREAD

**Issue by RobbieNesmith** [geopaparazzi/smash#272]
After updating to 1.91 I am unable to create GPS logs. When I press OK on the dialog box to name the log, the app crashes. After installing 1.90 I am able to see that most have no points but some have one point. I am still able to create location based notes.

I am using Android 14 on a Galaxy S24 Ultra.

**Comment by moovida** [comment]
Hi @RobbieNesmith , thank you so much for reporting. I have now been able to reproduce it on a device. Not sure what the problem is though. I will try to solve it asap, since that is a show stopper.

**Comment by moovida** [comment]
@RobbieNesmith could you do a few checks for me? 

Is it possible that the crash is due to the app not having the permission to execute background jobs? 
Can you check in the app info if the approriate permissions are given?

For some reason I am not able to allow the app to send notifications, which is necessary in android to use background location (which is what logs do).

![image](https://github.com/geopaparazzi/smash/assets/390250/d33c51d6-4663-4f90-9acb-7b08f319290f)

The above setting is disabled for me. Will have to find out why. Maybe you can check your settings too.

**Comment by RobbieNesmith** [comment]
Yes that seems to be the case for me too.

When I open "App notifications" in settings, I do not see SMASH in the list, but when I select "Show system apps" it will show up. I am able to toggle the checkbox in the list but it does not save the change. When I click the list item, the checkbox is disabled on the detail screen.

Screenshot of App notifications after showing system apps:
![image](https://github.com/geopaparazzi/smash/assets/6155690/f86e2e92-f34f-4561-80f0-1d4dd7fee52a)

Screenshot of SMASH's notification settings page
![image](https://github.com/geopaparazzi/smash/assets/6155690/c460caa0-23bc-4a74-8f79-65286ba13717)

**Comment by moovida** [comment]
Hi @RobbieNesmith , thanks for the feedback. 
I made a fix and deployed to f-droid a 1.9.2 version. As soon as it gets released (usually it takes 3-4 days), please let me know if it fixes this for you. You should have at first startup a new dialog asking to allow notifications.

**Comment by RobbieNesmith** [comment]
Thanks for the quick response!

I downloaded the new APK from the releases page here on Github and unfortunately it didn't seem to fix the issue.

I have some logcat logs for you that might be helpful.

[LogcatForSmash.txt](https://github.com/user-attachments/files/15938279/LogcatForSmash.txt)

Notably there's an error that says it was unable to create a notification due to a missing small icon. This error comes up in versions 1.9.1 and 1.9.2, but in 1.9.0 it says the location was blocked by permissions.

(Apologies for ridiculous formatting)
```logcat
2024-06-22 15:36:11.650 12911-12911 AndroidRuntime          eu.hydrologis.smash                  E  FATAL EXCEPTION: main
                                                                                                    Process: eu.hydrologis.smash, PID: 12911
                                                                                                    java.lang.RuntimeException: Unable to start service yukams.app.background_locator_2.IsolateHolderService@890ad5d with Intent { act=UPDATE_NOTIFICATION cmp=eu.hydrologis.smash/yukams.app.background_locator_2.IsolateHolderService (has extras) }: java.lang.IllegalArgumentException: Invalid notification (no valid small icon): Notification(channel=app.yu... shortcut=null contentView=null vibrate=null sound=null defaults=0x0 flags=0xa color=0xff1976d2 vis=PRIVATE semFlags=0x0 semPriority=0 semMissedCount=0)
                                                                                                    	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5286)
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2531)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:230)
                                                                                                    	at android.os.Looper.loop(Looper.java:319)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8918)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
                                                                                                    Caused by: java.lang.IllegalArgumentException: Invalid notification (no valid small icon): Notification(channel=app.yu... shortcut=null contentView=null vibrate=null sound=null defaults=0x0 flags=0xa color=0xff1976d2 vis=PRIVATE semFlags=0x0 semPriority=0 semMissedCount=0)
                                                                                                    	at android.app.NotificationManager.fixNotification(NotificationManager.java:770)
                                                                                                    	at android.app.NotificationManager.notifyAsUser(NotificationManager.java:749)
                                                                                                    	at android.app.NotificationManager.notify(NotificationManager.java:675)
                                                                                                    	at android.app.NotificationManager.notify(NotificationManager.java:651)
                                                                                                    	at yukams.app.background_locator_2.IsolateHolderService.v(SourceFile:1)
                                                                                                    	at yukams.app.background_locator_2.IsolateHolderService.onStartCommand(Unknown Source:140)
                                                                                                    	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5268)
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2531) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:230) 
                                                                                                    	at android.os.Looper.loop(Looper.java:319) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8918) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103) 
```

In 1.9.2 the notification does get created even though the app crashes, so that part of the fix works:

![image](https://github.com/geopaparazzi/smash/assets/6155690/200d9e7b-7f90-4da1-8ded-d7fcd4973004)

**Comment by moovida** [comment]
Hi @RobbieNesmith , thanks a ton for this. Since I am not able to reproduce the issue, I am a bit flying blind here.

I tried to create a fix based on your logcat (very helpful) and built an apk. Could you please install and test it before I release to fdroid? I would not want to create a set of invalid releases.

The download link is here: https://we.tl/t-erYvCIE2mS

**Comment by RobbieNesmith** [comment]
No luck unfortunately. I tried a couple more things:
1. I am using Lawnchair launcher so I tried switching back to Samsung OneUI Launcher
2. I tested it on my old phone (Galaxy S8, Android 9) and got the same result.

I'll get some more logcat logs tomorrow and see if anything looks promising

**Comment by moovida** [comment]
Thanks for the feedback @RobbieNesmith . I am really puzzeled. Did you by any chance try to change settings of the app (like permissions, background notifications) to see if something changes?

**Comment by RobbieNesmith** [comment]
I checked the logcat logs and it looks the same as before (Invalid small icon). The strange thing is, once the app crashes the notification (icon and all) eventually appears
![image](https://github.com/geopaparazzi/smash/assets/6155690/2ac2aa95-eadd-479e-880a-c2a8c0729a3b)

Looking at the perquests I saw that the location is set as "Allow only while using the app", so I switched that to "Allow all the time" but that didn't help. Also "Music and Audio" was available but not enabled, so I enabled that but that didn't help either.

Here's what permissions are active:
![image](https://github.com/geopaparazzi/smash/assets/6155690/997a2f94-f044-4635-80d8-23e6f276174b)

**Comment by moovida** [comment]
Hi @RobbieNesmith , would you mind trying this version also? https://we.tl/t-1RSxhU5Rbe
On one new device I tested (Android 13) it crashed to me at first due to an issue with not being able to show logs with less than 2 points. I wonder if that might concur to you issue. Finger very crossed. Thanks

**Comment by RobbieNesmith** [comment]
That sounds promising! Looks like the wetransfer link expired though

**Comment by moovida** [comment]
Oh sorry, I tested it on a device and it crashed, so I removed it, thinking you had it already. This thing coming from the locator gps library is a real mess. 
I am trying something new right now. If it works I submit it to your test also. Thanks

**Comment by RobbieNesmith** [comment]
That works! Thanks!

**Comment by moovida** [comment]
Wooo, great! Then I am going to do an fdroid release and after vacation take some time to think about a new location library to use.
Thanks for the support.
